Add documentation and license
energinet-singularity/forecast-parser pull request #20
Opened 2022-01-17 13:30 UTC by swedchef

Add license and notice files.
Update README with a full description of the project

2022-01-21 10:40 UTC, vjsaini75 requested changes
file handling : how many files normally should be under this folder, is there some indication if files are not processed. 

kafka messages/output : not clear for last line, need some expalnation
"Please note that not all above data-types can be found in all packages as the different forecast-types deliver different data-subsets."

2022-01-21 11:27 UTC, CodeWitten approved these changes
Good looking documentation. Great work on describing data structures and variables. I was easily able to spin it up it a container following the "getting started" section, nice that you provide a test data set.

I miss a more detailed introduction/overview of what the product actually does and its usecase, i think we are jumping to quick into the details. I understand the purpose of the product and the functionality, but outsiders won't. I however suggest we leave it "as-is" until we have a suggestion for templace for readme, as i do not yet have a good suggestion on how it should be covered. Once we have some initial template we can have a look at your readme and try aligning it with the template.

2022-01-21 11:30 UTC, CodeWitten commented
> kafka messages/output : not clear for last line, need some expalnation "Please note that not all above data-types can be found in all packages as the different forecast-types deliver different data-subsets."

i agree with @vjsaini75 . I do not understand what is ment.

2022-01-24 13:21 UTC, vjsaini75 approved these changes

2022-01-24 13:22 UTC, merged