Made kSQL validation via REST api
energinet-singularity/forecast-parser pull request #3
Opened 2021-11-23 15:09 UTC by swedchef

Will resolve #2 and in general make life better.. !

2021-11-24 14:06 UTC, jacobcrawford requested changes
The port of the ksql server should be a part of the input and not hardcoded.

2021-11-25 06:36 UTC, jacobcrawford requested changes
Almost there! Looks beautiful :)

2021-11-25 06:36 UTC, jacobcrawford commented on Dockerfile
>  CMD ["python3", "-u", "forecast-import.py"]
Add newline at the end of file.

2021-11-25 06:36 UTC, jacobcrawford commented on ksql-config.json
> +}
Add newline at the end of file.

2021-11-25 06:43 UTC, swedchef commented on Dockerfile
>  CMD ["python3", "-u", "forecast-import.py"]
Added the newline - thanks

2021-11-25 06:43 UTC, swedchef commented on ksql-config.json
> +}
Added the newline - thanks

2021-11-25 06:59 UTC, jacobcrawford approved these changes
This is awesome!

2021-11-25 07:12 UTC, merged