Feature/switch to api
energinet-singularity/forecast-parser pull request #36
Opened 2022-06-10 10:53 UTC by swedchef

Major change - switch from kafka to API.

2022-06-14 06:38 UTC, vjsaini75 requested changes
code looks very nice. but need smal description on specail methods

2022-06-14 07:38 UTC, cjjohansen commented on app/parsers.py
> +def get_dmi_helpers() -> dict:
try to avoid calling things helpers. Be more specific. 
maybe something like  "dmi_headers_to_standard_headers"
what would we call the standard ? "energi_net standard".
Maybe key and value should be inverted so the standard identifier is the key.?

2022-06-14 07:39 UTC, cjjohansen commented on app/parsers.py
> +    The DMI files have headers that need to be translated into standard names
DMI or conwx ?

2022-06-14 07:41 UTC, cjjohansen commented on app/parsers.py
> +def conwx_parser(file_contents: list[str], helpers: dict) -> pd.DataFrame:
consider splitting conwx and dmi stuff into two seperate files

2022-06-14 07:43 UTC, cjjohansen commented on app/parsers.py
> +        df_out["temperature_2m"] += 273.15
magic numbers. add to constant maybe in seperate file
What is 273.15 ?

2022-06-14 11:55 UTC, swedchef commented on app/parsers.py
> +def get_dmi_helpers() -> dict:
In this case it is intended to be generic, as the dict can hold different items depending on what is needed for parsing the file. For DMI-formatted files that is currently a header mapping, while it for ConWx-formatted files is both a header mapping and a set of geographical coordinates. Please let me know if you have a better suggestion, but i came out with "helper" as the most specific adequately generic naming i could think of. If you have a suggestion, please put it forward.

It is not possible to map the key-value sets inverted as the relationship is not 1:1 (or, at least that would require splitting the helper between the two different dmi-style files). Currently we have multiple file-headers that should translate to a single DF-header making it impossible to turn around.

2022-06-14 11:55 UTC, swedchef commented on app/parsers.py
> +    The DMI files have headers that need to be translated into standard names
oops!

2022-06-14 12:01 UTC, swedchef commented on app/parsers.py
> +        df_out["temperature_2m"] += 273.15
Well, not so magic, it is a constant much like pi - to calculate temperature in kelvin given a temperature in celcius, but i can give it a const to make it easier to understand. On it's way!

2022-06-14 12:33 UTC, swedchef commented on app/parsers.py
> +def conwx_parser(file_contents: list[str], helpers: dict) -> pd.DataFrame:
Could you elaborate on how that would benefit? It would require an extra import in main.py and test-files. As the functions would not be renamed, the code would not really change and thereby, as far as i can see, it just adds an unnecessary overhead - but perhaps i am overseeing something?

2022-06-14 12:35 UTC, swedchef commented on app/parsers.py
> +def get_dmi_helpers() -> dict:
I will resolve - if you disagree, please just un-resolve.

2022-06-14 13:25 UTC, xandvenerginet commented on README.md
> +Older versions are not included in the README version history. For detaols on them, see the main-branch commit history, but beware: it was the early start and it was part of the learning curve, so it
```suggestion
Older versions are not included in the README version history. For details on them, see the main-branch commit history, but beware: it was the early start and it was part of the learning curve, so it is not pretty. They are kept as to not disturb the integrity of the history.
```

2022-06-14 14:17 UTC, vjsaini75 submitted a review, later dismissed

2022-06-15 06:43 UTC, cjjohansen commented on app/parsers.py
> +def conwx_parser(file_contents: list[str], helpers: dict) -> pd.DataFrame:
I would always do it to get smaller files.
and you would get more specific file names.
and your dependencies (imports would be more specific one for dmi and one for conwx) imagine you should add more formats. Then would you like to append to one file or simply make a new file.

2022-06-15 06:49 UTC, cjjohansen commented on app/parsers.py
> +def get_dmi_helpers() -> dict:
I think we need to sit together to discuss it if we want to go into it. I might need to understnad the code better.
My problem is that I have to read the code inside the function to understand what the function does. That forces me to read all code to understand. Its more efficient if can just read the function name. To judge whether its should be generic or not I would have to study the code further.

2022-06-15 07:11 UTC, cjjohansen commented on app/main.py
> +        self.helpers = helpers
This could be any thing. The reader has no clue what these helpers are.

2022-06-15 07:16 UTC, cjjohansen commented on app/main.py
> +    __df: pd.DataFrame = None
What are weather forescast settings?
One should try to follow so called single responsibility rule. A class should do one thing well.
The file handling parts should probably belong to a parser class. Where as WatherForecast should only contain weather forecast data and psossibly methods/functions that can manipulate data (if needed) My guess is that Weather forecast class in this case should strictly contain data and nothing else. Maybe the easiest fix is to rename the class to WeatherForecastParser

2022-06-15 07:22 UTC, cjjohansen commented on app/main.py
> +    type : str
consider using even morespecific name. I would suggest type -> forecast_provider (or what you would call dmi and ConWx)
We should also restrict the type to be either  "dmi" or "convw" not any type.  Use Enums
https://devenum.com/how-to-convert-enum-to-string-in-python/

2022-06-15 07:27 UTC, swedchef commented on app/configuration.py
> +def get_settings(load_from_env: bool = True) -> Settings:
As far as i can see, there will never be a situation where we will NOT want to take the environment variables, as this is how configurations are made. But @cjjohansen argued that automatically overwriting the default-values with the environment settings without giving the user the chance to say "no thank you" or even know that it is happening was bad practice, so to comply with that i made this function.

2022-06-15 07:29 UTC, swedchef commented on app/main.py
> +        self.__api[self.__dbname] = pd.concat(forecast_dict, ignore_index=True)
Agreed.

2022-06-15 07:30 UTC, swedchef commented on app/main.py
> +                log.info(f"Parsing file '{file}' as type {parse_list[file].type}.")
Does it matter? I can move it, but i don't really think it changes anything.

2022-06-15 08:24 UTC, swedchef commented on app/main.py
> +    """List files in 'path' where file name fits 'filter' and sort with oldest first"""
I'm not sure i get what you are saying. I would argue it is a single thing - listing all files in a folder, sorted by age (which the name indicates), with the added option of setting a filter. If you had to name the function according to any possible parameter, i would argue the naming would get out of hand. Or did i misunderstand what you meant?

2022-06-15 08:24 UTC, swedchef commented on app/main.py
> +    schedule.every(1).minutes.do(forecast_manager.ScanPath, path=settings.FORECAST_PATH)
I think you found a BUG! :/

2022-06-15 08:32 UTC, swedchef commented on app/main.py
> +        self.helpers = helpers
Did you read my response to your last comment on the same subject? I am happy to use another meaningful name, but the thing here is the function/class acts more or less like a wrapper - so i would like it to maintain some element of generic'ness to allow this abstraction to exist.

The idea is the "helpers" is a dictionary containing elements/configurations/lookups that are specific for the parser to be able to run. In case we get a new format of weather forecast in the future, i would prefer that the wrapper is generic enough to wrap the new configuration (and perhaps allow os to only edit the parsers.py file and not all files).

I actually tried to use some of the mentality that was in the design principle guide you referenced.

2022-06-15 09:10 UTC, swedchef commented on app/main.py
> +    __df: pd.DataFrame = None
You lost me here. The "WeatherForecast" class does specifically not handle files. The "load" method takes a list of strings (usually loaded from a file though) and sends to the parser. I have renamed the parameter "file_contents" to "forecast_data" to logically allow another source.

2022-06-15 12:40 UTC, stigsberg commented on app/main.py
> +    """List files in 'path' where file name fits 'filter' and sort with oldest first"""
in short I would change name to: "list_filtered_files_by_age"

2022-06-15 12:48 UTC, swedchef commented on app/main.py
> +    """Load file 'file_path' into list and remove it if 'remove_file_after_load'"""
The error handling is imperfect. I modified it in the load_file func. Thanks.

2022-06-15 12:53 UTC, swedchef commented on README.md
> +The container has an option to generate mock-data. This is done by taking the test-data files and changing their timestamps and dumping them into the input directory. This can be used if real forecas
You are correct sir - but i have resolved it by fixing the delay in stead and removing the comment further down.

2022-06-15 13:37 UTC, swedchef commented on app/main.py
> +        """Check for new files in path and update manager if relevant
This is as intended. Fixed at other place you referenced.

2022-06-15 13:47 UTC, swedchef commented on app/main.py
> +        self.helpers = helpers
Will resolve for now - we can make an issue if we want to spend more time on it :)

2022-06-15 13:47 UTC, swedchef commented on app/main.py
> +    __df: pd.DataFrame = None
Will resolve for now - we can make an issue if we want to spend more time on it :)

2022-06-16 06:43 UTC, vjsaini75 approved these changes

2022-06-16 06:56 UTC, merged